
server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: UserCenter
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.113.192.175:3306/huanzhan?userSSL=false&serverTimezone=GMT%2B8
#    url: jdbc:mysql://localhost:3306/huanzhan?userSSL=false&serverTimezone=GMT%2B8
    username: huanzhan
#    username: root
    password: 123456


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
huanzhan:
  client:
    access-key: huanzhan
    secret-key: huanzhan

